version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: expense-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expense_management
      MYSQL_USER: expense_user
      MYSQL_PASSWORD: expense_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - expense-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/expense_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: expense_user
      SPRING_DATASOURCE_PASSWORD: expense_password
      JWT_SECRET: mySecretKey123456789012345678901234567890
      FILE_UPLOAD_DIR: /app/uploads
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mysql
    networks:
      - expense-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expense-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - expense-network

volumes:
  mysql_data:

networks:
  expense-network:
    driver: bridge

